
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-configmap-role
  namespace: locker-test-ns
rules:
- apiGroups: [""] 
  resources: ["configmaps"] 
  verbs: [ "list", "get", "watch", "patch" ]
